#!/usr/bin/env bash
# Run Apache on the holbertonschool/265-0 Docker container.
service apache2 start
#!/usr/bin/env bash
# run apache on holbertonschool/265-0 container

echo "ServerName localhost" >> /etc/apache2.conf
service apache2 start
#!/usr/bin/env bash
# run apache on holbertonschool/265-0 container

echo "ServerName localhost" >> /etc/apache2.conf
service apache2 start